# Generated by Django 5.1.3 on 2024-12-03 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Portaobjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to='imagenes/')),
                ('descripcion', models.TextField()),
                ('fecha_subida', models.DateField(auto_now_add=True)),
                ('portaobjeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.portaobjeto')),
            ],
        ),
        migrations.CreateModel(
            name='PortaobjetoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.categoria')),
                ('portaobjeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.portaobjeto')),
            ],
            options={
                'unique_together': {('portaobjeto', 'categoria')},
            },
        ),
        migrations.AddField(
            model_name='portaobjeto',
            name='categorias',
            field=models.ManyToManyField(through='mi_aplicacion.PortaobjetoCategoria', to='mi_aplicacion.categoria'),
        ),
        migrations.AddField(
            model_name='portaobjeto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.usuario'),
        ),
    ]
